#!/usr/bin/env bash
set -euo pipefail

# Script to generate tsdoc monorepo coverage and evidence for corpus.
# Usage: ./run-monorepo-corpus.sh <commit_sha> <output_dir>
# Example: ./run-monorepo-corpus.sh 98644d0192b82c5a5b0b48adadc48c4796456d85 ./experiments/wp5/wp5.6/

# Source nvm to manage Node versions
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Use Node 18
nvm use 18
echo "Using Node $(node --version)"

# Defaults
TSDOC_REPO="${TSDOC_REPO:-/tmp/tsdoc-real}"
COMMIT_SHA="${1:-}"
OUTPUT_DIR="${2:-./experiments/wp5/wp5.6}"

if [[ -z "$COMMIT_SHA" ]]; then
  echo "Error: Commit SHA is required"
  echo "Usage: $0 <commit_sha> [output_dir]"
  exit 1
fi

# Validate COMMIT_SHA format: hex string, 4 to 40 characters
if ! [[ "$COMMIT_SHA" =~ ^[0-9a-f]{4,40}$ ]]; then
  echo "Error: COMMIT_SHA must be hex 4-40 chars"
  exit 1
fi

mkdir -p "$OUTPUT_DIR"

# Worktree directory for the tsdoc-coverage.sh script (it uses its own worktree)
# We'll let the tsdoc-coverage.sh handle the worktree.

# Temporary directory for tsdoc-coverage.sh output
TEMP_OUTPUT_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_OUTPUT_DIR"' EXIT

# Generate coverage using the existing tsdoc-coverage.sh script
echo "Generating coverage using tsdoc-coverage.sh..."
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
"$SCRIPT_DIR/tsdoc-coverage.sh" "$COMMIT_SHA" "$TEMP_OUTPUT_DIR"

# Find the coverage artifact generated by tsdoc-coverage.sh
COVERAGE_ARTIFACT=$(ls "$TEMP_OUTPUT_DIR"/coverage-*.json | head -n 1)
if [[ -z "$COVERAGE_ARTIFACT" ]]; then
  echo "Error: No coverage artifact found in $TEMP_OUTPUT_DIR"
  exit 1
fi

# Copy the coverage artifact to the output directory with a predictable name
COVERAGE_DEST="$OUTPUT_DIR/tsdoc-monorepo-coverage-${COMMIT_SHA}.json"
cp "$COVERAGE_ARTIFACT" "$COVERAGE_DEST"
echo "Coverage artifact copied to $COVERAGE_DEST"

# Generate evidence using the engine CLI
if [ -d "$SCRIPT_DIR/../src" ]; then
  echo "Running engine check to generate evidence JSON..."
  # Determine base commit (parent of the commit) for the check
  # We'll get the parent SHA via git show in the tsdoc repo
  cd "$TSDOC_REPO"
  PARENT_SHA=$(git show -s --format=%P "$COMMIT_SHA" | awk '{print $1}')
  if [ -z "$PARENT_SHA" ]; then
    # If no parent (initial commit), we'll skip the check
    echo "Warning: Could not determine parent commit for $COMMIT_SHA, skipping evidence generation."
  else
    EVIDENCE_DEST="$OUTPUT_DIR/tsdoc-monorepo-evidence-${COMMIT_SHA}.json"
    npx tsx "$SCRIPT_DIR/../src/cli.ts" check --base "$PARENT_SHA" --coverage-file "$COVERAGE_DEST" --json > "$EVIDENCE_DEST"
    echo "Evidence JSON saved to $EVIDENCE_DEST"
  fi
else
  echo "Warning: Could not locate original repo, skipping evidence generation."
fi

echo "Tsdoc monorepo corpus processing successful for commit $COMMIT_SHA"
echo "Coverage artifact: $COVERAGE_DEST"
echo "Evidence JSON: $EVIDENCE_DEST (if generated)"